#!/bin/bash
set -e
HERE=$(dirname $0)
ROOT=$HERE/..

TEST_EXE=vty-ui-tests
TEST=$HERE/../test
BUILDDIR=$TEST/dist
cabal configure -f testing --builddir=$BUILDDIR
cabal build --builddir=$BUILDDIR --ghc-options="-Wall -Werror"

$BUILDDIR/build/$TEST_EXE/$TEST_EXE 2>/dev/null
