#!/bin/bash
set -e
HERE=$(dirname $0)
ROOT=$HERE/..

TEST=$HERE/../test
BUILDDIR=$TEST/dist
cabal configure -f testing --builddir=$BUILDDIR
cabal build --builddir=$BUILDDIR --ghc-options="-Wall -Werror"

# No tests yet, so for now we just compile the package on record.
# cd test
# ./dist/build/test/test data
